[package]
name = "veridian-controller"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
signal-hook = "0.3.17"
toml = "0.8.13"
clap = { version = "4.5.4", features = ["derive"] }
chrono = "0.4.38"
