sampling_window_size = 5
temp_thresholds = [52, 62, 72, 84]
fan_speeds = [46, 62, 80, 100]
fan_speed_floor = 46
fan_speed_ceiling = 100
incr_weight = 0.5
decr_weight = 0.2
hysteresis = 3
global_delay = 2
post_adjust_delay = 4
smooth_mode = true
smooth_mode_fan_step = 5
debug_mode = true
