temperatures = [52, 72, 82, 89]
fan_speeds = [46, 62, 80, 100]
fan_speed_floor = 46
fan_speed_ceiling = 100
fan_hysteresis = 3
window_size = 5
global_timer = 2
smooth_mode = true
disable_lo_temp_fan_control = true
