name: Build and Upload Binary

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "main build"
        required: true
        default: "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get project version
        id: get_version
        run: |
          VERSION=$(sed -nE 's/^version = "(.*)"/\1/p' Cargo.toml)
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Build project
        run: |
          chmod +x ./build.sh
          export CI=${{ env.CI }}
          ./build.sh
          cd ./target/appimage

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: veridian-controller
          path: veridian-controller_${{ steps.get_version.outputs.VERSION }}.tar.gz
